### ISSUE TITLE
as a user I want to retrieve map information so that I can plan my trip

### ISSUE THREAD

**Issue by tlavette** [ceceliacreates/project-green#6]
Requirements:
- [x] Add checkbox that allows user to choose their existing location as the search input
- [x] Take trail name information from Hiking Trails API JSON response and render to search result
- [x] Take trail length information from Hiking Trails API JSON response and render to search result
- [x] Take trail address and based on zip code or user location, render distance from user to search result
- [x] Using the Hiking Trails API, render a map thumbnail image for each displayed search result
- [x] A link to directions to the hiking trial head address from current location (Google Maps)

**Comment by ceceliacreates** [comment]
Issue completed
